### ISSUE TITLE
Not an Issue - Is there any possibility to have parameter Name rather than integers

### ISSUE THREAD

**Issue by GouthamiKoduri** [KennethanCeyer/metric-parser#1]
Is there any possibility to have parameters rather than integers
For Ex: a^2+(2*a*b)+b^2 -- so a & b are treated as parameters
cost = price * margin% like so

Is there any functionality like this

**Comment by KennethanCeyer** [comment]
Hello @GouthamiKoduri !

Sorry for late reply.

This feature is planned to be added to `v1.0.2` version.

In the past, the core of the repository code has been **entirely** written **entirely** in new code.

It follows the AST (Abstract Syntax Tree) based formal change algorithm.

[It has a roadmap to support more](https://github.com/KennethanCeyer/metric-parser/tree/feature/migrate-typescript#roadmap) features (function expressions, variable definition and binding, deep expression verification).

It provides all the results same as before, but it is designed to be extensible so that developers can create own tree they want by injecting abstract class.

At the beginning of April this month, we will release the version back to v1.0.0, which is provided as a typescript. (Of course, javascript is also provided and can be run in a browser.)

We are creating automated test logic for all logic, and we are aiming for coverage 90% coverage.

In addition, we plan to create a developer wiki and contribution document.

It would be nice if you could discuss the new features more intensively in early April.

Please let me know if you have any missing additions from the above roadmap!

Thank you.
